-- Show ingredient-matched gift baskets on Tilda Flow article pages.
-- The browser sends only the article alias; filter rules stay server-side.

create table if not exists public.article_product_filters (
  id bigint generated by default as identity primary key,
  alias text not null unique,
  filter_type text not null,
  filter_value text not null,
  title text,
  subtitle text,
  limit_count integer not null default 8,
  enabled boolean not null default true,
  cluster_key text,
  cluster_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint article_product_filters_alias_format
    check (alias ~ '^[a-z0-9][a-z0-9-]*$'),
  constraint article_product_filters_filter_type
    check (filter_type in ('tag', 'ingredient', 'ingredient_contains')),
  constraint article_product_filters_filter_value
    check (nullif(trim(filter_value), '') is not null),
  constraint article_product_filters_limit_count
    check (limit_count between 1 and 12)
);

comment on table public.article_product_filters is
  'Server-side mapping from Tilda article aliases to safe product ingredient filters.';

comment on column public.article_product_filters.filter_value is
  'Tag, exact ingredient, or pipe-separated contains variants controlled by the server.';

create or replace function public.touch_article_product_filters_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists article_product_filters_touch_updated_at
  on public.article_product_filters;

create trigger article_product_filters_touch_updated_at
before update on public.article_product_filters
for each row execute function public.touch_article_product_filters_updated_at();

create index if not exists idx_article_product_filters_cluster
  on public.article_product_filters (cluster_key, cluster_order)
  where enabled = true;

create index if not exists idx_product_ingredients_tag_product_key
  on public.product_ingredients (tag, product_key);

create index if not exists idx_products_catalog_available_category
  on public.products_catalog (category_slug, product_key)
  where available = true;

alter table public.article_product_filters enable row level security;

revoke all on table public.article_product_filters from public, anon, authenticated;
grant all on table public.article_product_filters to service_role;
grant usage, select on sequence public.article_product_filters_id_seq to service_role;
revoke all on function public.touch_article_product_filters_updated_at() from public;

insert into public.article_product_filters (
  alias,
  filter_type,
  filter_value,
  title,
  subtitle,
  limit_count,
  enabled,
  cluster_key,
  cluster_order
)
values
  (
    'podarochnye-korziny-s-syrom',
    'tag',
    'cheese',
    'Подарочные корзины с сыром',
    'Актуальные наборы SweetGift, в составе которых есть сыр',
    8,
    true,
    'cheese-baskets',
    0
  ),
  (
    'gorgonzola-v-podarochnykh-korzinakh',
    'ingredient_contains',
    'горгонзол|gorgonzol',
    'Подарочные корзины с горгонзолой',
    'Корзины SweetGift с горгонзолой в составе',
    8,
    true,
    'cheese-baskets',
    1
  ),
  (
    'rokfor-v-podarochnykh-korzinakh',
    'ingredient_contains',
    'рокфор|rockfor',
    'Подарочные корзины с рокфором',
    'Корзины SweetGift с сыром рокфор в составе',
    8,
    true,
    'cheese-baskets',
    2
  ),
  (
    'kamamber-v-podarochnykh-korzinakh',
    'ingredient_contains',
    'камамбер|camembert',
    'Подарочные корзины с камамбером',
    'Корзины SweetGift с камамбером в составе',
    8,
    true,
    'cheese-baskets',
    3
  )
on conflict (alias) do update
set
  filter_type = excluded.filter_type,
  filter_value = excluded.filter_value,
  title = excluded.title,
  subtitle = excluded.subtitle,
  limit_count = excluded.limit_count,
  enabled = excluded.enabled,
  cluster_key = excluded.cluster_key,
  cluster_order = excluded.cluster_order,
  updated_at = now();

create or replace function public.get_article_products(article_alias text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_rule public.article_product_filters%rowtype;
  v_result jsonb;
begin
  if article_alias is null
     or length(article_alias) > 200
     or article_alias !~ '^[a-z0-9][a-z0-9-]*$' then
    return null;
  end if;

  select *
  into v_rule
  from public.article_product_filters
  where alias = article_alias
    and enabled = true;

  if not found then
    return null;
  end if;

  with
  needles as (
    select lower(trim(value)) as value
    from regexp_split_to_table(v_rule.filter_value, '\s*\|\s*') as parts(value)
    where nullif(trim(value), '') is not null
  ),
  matched_products as (
    select
      p.product_key,
      p.title,
      p.url,
      p.image,
      p.price,
      p.composition,
      p.category_slug,
      max(
        case
          when v_rule.filter_type = 'ingredient'
               and lower(trim(coalesce(pi.ingredient_raw, ''))) =
                   lower(trim(v_rule.filter_value))
            then 100
          when v_rule.filter_type = 'ingredient_contains'
               and exists (
                 select 1
                 from needles n
                 where lower(trim(coalesce(pi.ingredient_raw, ''))) = n.value
               )
            then 100
          when v_rule.filter_type = 'ingredient_contains'
               and exists (
                 select 1
                 from needles n
                 where position(n.value in lower(coalesce(pi.ingredient_raw, ''))) = 1
               )
            then 90
          when v_rule.filter_type = 'ingredient_contains' then 80
          else 50
        end
      ) as match_precision,
      array_agg(distinct pi.ingredient_raw)
        filter (where pi.ingredient_raw is not null) as matched_ingredients
    from public.product_ingredients pi
    join public.products_catalog p on p.product_key = pi.product_key
    where p.available = true
      and (
        lower(coalesce(p.category_slug, '')) ~ '(korzin|basket)'
        or (
          lower(coalesce(p.category_slug, '')) in ('', 'tproduct')
          and (
            lower(coalesce(p.title, '')) like '%корзин%'
            or lower(coalesce(p.product_key, '')) like '%korzin%'
          )
        )
      )
      and case v_rule.filter_type
        when 'tag' then
          lower(trim(coalesce(pi.tag, ''))) =
          lower(trim(v_rule.filter_value))
        when 'ingredient' then
          lower(trim(coalesce(pi.ingredient_raw, ''))) =
          lower(trim(v_rule.filter_value))
        when 'ingredient_contains' then
          exists (
            select 1
            from needles n
            where position(n.value in lower(coalesce(pi.ingredient_raw, ''))) > 0
               or position(n.value in lower(coalesce(pi.ingredient_normalized, ''))) > 0
          )
        else false
      end
    group by
      p.product_key,
      p.title,
      p.url,
      p.image,
      p.price,
      p.composition,
      p.category_slug
  ),
  popularity as (
    select
      e.product_key,
      sum(
        case e.event_type
          when 'purchase' then 10
          when 'add_to_cart' then 4
          when 'favorite' then 3
          when 'listing_click' then 2
          when 'view' then 1
          else 0
        end
      )::bigint as popularity_score
    from public.product_events e
    join matched_products m on m.product_key = e.product_key
    group by e.product_key
  ),
  ordered_products as (
    select
      m.*,
      coalesce(pop.popularity_score, 0) as popularity_score
    from matched_products m
    left join popularity pop on pop.product_key = m.product_key
    order by
      case when v_rule.filter_type = 'tag' then 0 else m.match_precision end desc,
      coalesce(pop.popularity_score, 0) desc,
      m.price asc nulls last,
      m.title asc
    limit v_rule.limit_count
  ),
  navigation as (
    select
      f.alias,
      f.title,
      f.cluster_order
    from public.article_product_filters f
    where f.enabled = true
      and f.cluster_key = v_rule.cluster_key
      and f.alias <> v_rule.alias
    order by f.cluster_order, f.title
  )
  select jsonb_build_object(
    'alias', v_rule.alias,
    'title', v_rule.title,
    'subtitle', v_rule.subtitle,
    'products', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'product_key', p.product_key,
          'title', p.title,
          'url', p.url,
          'price', p.price,
          'image', p.image,
          'composition', p.composition,
          'matched_ingredients', p.matched_ingredients,
          'popularity', p.popularity_score
        )
        order by
          case when v_rule.filter_type = 'tag' then 0 else p.match_precision end desc,
          p.popularity_score desc,
          p.price asc nulls last,
          p.title
      )
      from ordered_products p
    ), '[]'::jsonb),
    'navigation', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'alias', n.alias,
          'title',
            case
              when n.alias = 'podarochnye-korziny-s-syrom'
                then 'Все материалы о сырах в подарочных корзинах'
              else n.title
            end,
          'url', '/stati/' || n.alias
        )
        order by n.cluster_order, n.title
      )
      from navigation n
    ), '[]'::jsonb)
  )
  into v_result;

  return v_result;
end;
$$;

comment on function public.get_article_products(text) is
  'Returns configured available gift baskets and cluster navigation for one Tilda article alias.';

revoke all on function public.get_article_products(text) from public;
grant execute on function public.get_article_products(text) to anon, authenticated;
