create table if not exists public.tilda_catalog_csv_imports (
  id bigint generated by default as identity primary key,
  filename text not null,
  file_sha256 text not null,
  row_count integer not null,
  imported_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb,
  constraint tilda_catalog_csv_imports_row_count_nonnegative check (row_count >= 0)
);

create table if not exists public.tilda_catalog_csv_rows (
  tilda_uid text primary key,
  import_id bigint not null references public.tilda_catalog_csv_imports(id) on delete restrict,
  parent_uid text,
  external_id text,
  sku text,
  brand text,
  category text,
  title text not null,
  description text,
  product_text text,
  photos jsonb not null default '[]'::jsonb,
  price numeric,
  old_price numeric,
  quantity numeric,
  unlimited boolean not null default false,
  editions text,
  modifications text,
  weight numeric,
  length numeric,
  width numeric,
  height numeric,
  url text,
  raw jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  imported_at timestamptz not null default now(),
  constraint tilda_catalog_csv_rows_uid_not_blank check (length(trim(tilda_uid)) > 0),
  constraint tilda_catalog_csv_rows_photos_array check (jsonb_typeof(photos) = 'array'),
  constraint tilda_catalog_csv_rows_quantity_nonnegative check (quantity is null or quantity >= 0)
);

create index if not exists tilda_catalog_csv_rows_parent_uid_idx
  on public.tilda_catalog_csv_rows(parent_uid) where active is true;
create index if not exists tilda_catalog_csv_rows_external_id_idx
  on public.tilda_catalog_csv_rows(external_id) where active is true;
create index if not exists tilda_catalog_csv_rows_import_id_idx
  on public.tilda_catalog_csv_rows(import_id);

alter table public.tilda_catalog_csv_imports enable row level security;
alter table public.tilda_catalog_csv_rows enable row level security;
revoke all on public.tilda_catalog_csv_imports, public.tilda_catalog_csv_rows from anon, authenticated;
grant all on public.tilda_catalog_csv_imports, public.tilda_catalog_csv_rows to service_role;

comment on table public.tilda_catalog_csv_rows is
  'Latest full Tilda Catalog CSV snapshot. Blank Quantity is stored as unlimited=true, not zero.';
