-- SweetGift nightly pipeline observability.

create table if not exists public.system_job_logs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  processed_count bigint not null default 0,
  duration_ms bigint,
  error_message text,
  details jsonb not null default '{}'::jsonb
);

alter table public.system_job_logs
  add column if not exists job_name text,
  add column if not exists started_at timestamptz default now(),
  add column if not exists finished_at timestamptz,
  add column if not exists status text default 'running',
  add column if not exists processed_count bigint default 0,
  add column if not exists duration_ms bigint,
  add column if not exists error_message text,
  add column if not exists details jsonb default '{}'::jsonb;

create index if not exists system_job_logs_job_started_idx
  on public.system_job_logs (job_name, started_at desc);

create index if not exists system_job_logs_status_started_idx
  on public.system_job_logs (status, started_at desc);

alter table public.system_job_logs enable row level security;

revoke all on table public.system_job_logs from anon, authenticated;
grant all on table public.system_job_logs to service_role;

create or replace function public.get_system_pipeline_health()
returns jsonb
language sql
security definer
set search_path = public
as $$
  with expected(job_name) as (
    values
      ('import-yml-products'::text),
      ('import-articles-index'::text),
      ('classify-articles'::text),
      ('send-daily-report'::text)
  ),
  latest as (
    select distinct on (l.job_name)
      l.job_name,
      l.started_at,
      l.finished_at,
      l.status,
      l.processed_count,
      l.duration_ms,
      l.error_message,
      l.details
    from public.system_job_logs l
    join expected e on e.job_name = l.job_name
    order by l.job_name, l.started_at desc
  )
  select jsonb_build_object(
    'generated_at', now(),
    'jobs', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'job_name', e.job_name,
          'started_at', l.started_at,
          'finished_at', l.finished_at,
          'status', coalesce(l.status, 'never'),
          'processed_count', coalesce(l.processed_count, 0),
          'duration_ms', l.duration_ms,
          'error_message', l.error_message,
          'details', coalesce(l.details, '{}'::jsonb),
          'fresh', coalesce(l.finished_at, l.started_at) >= now() - interval '30 hours'
        )
        order by e.job_name
      ),
      '[]'::jsonb
    )
  )
  from expected e
  left join latest l on l.job_name = e.job_name;
$$;

revoke all on function public.get_system_pipeline_health() from public, anon, authenticated;
grant execute on function public.get_system_pipeline_health() to service_role;
